### ISSUE TITLE
error reporting snippet appears even if everything is ok

### ISSUE THREAD

**Issue by carocad** [hiposfer/hive#125]
See attached screenshot.

There is nothing wrong with my current setup but I still see it on screen.

![screenshot_2018-07-20-11-17-47-853_host exp exponent](https://user-images.githubusercontent.com/10408729/42994603-cd4b02c4-8c0e-11e8-9f46-2c320f929b7f.png)

**Comment by mehdisadeghi** [comment]
It seems that this is a known Android problem: https://github.com/facebook/react-native/issues/1322.
