### ISSUE TITLE
allow to switch cities only on supported areas

### ISSUE THREAD

**Issue by carocad** [hiposfer/hive#131]
Currently we have 3 hardcoded cities for hive to choose.

If the kamal server being used does not support that city, it would fail silently.

I think it would be best if hive would only show the areas that are supported by the server

Most probably we would need some extra information for it to work together with kamal.

@mehdisadeghi since this would allow you to use the Freiburg area instead of relying on hardcoded values, would you like to tackle this one?

**Comment by mehdisadeghi** [comment]
@carocad I'll see what I can do :)
