### ISSUE TITLE
disallow usage on gps off

### ISSUE THREAD

**Issue by carocad** [hiposfer/hive#23]
Given that our app focuses on routing, I think the best usability would be achieved if we disallow using the app without GPS. 

- This is due to our dependency of track uploading based on user gps
- If we want to provide instant routing knowing the user's current location is a must

@mehdisadeghi request for comments

**Comment by mehdisadeghi** [comment]
Is there any benefit in preventing user from interacting with the app when GPS is off? Or the other way round, do we lose anything if users open the app without GPS? What if the GPS is not off but unavailable due to weak signal or being in a dead spot, how our app should behave?

**Comment by carocad** [comment]
I see several benefits and disadvantage related to this.

benefits:
- automatic recognition of current region/city (useful when traveling)
- bias geocode result through current user location
- automatic track recording without manually triggering it
- for people concerned about their privacy we could offer a "do not track me" (paid) option to disable the need for a gps to protect their privacy. Their gps could still be used but no track should be recorded

disadvantages (of not requiring it):
- search and forget: a user could simply search for the information needed and leave the app immediately afterwards without contributing anything to the community (free version ?)
- usability: the "start" address would get lost every time the app is closed. Therefore forcing the user to re-enter it every time.
- configuration lost **: a user would need to manually change his current region in order to use the routing service after traveling from one place to another.
- allowing the usage of the app without gps also means that the user could initially enable the gps and then disable it some time after. This would mean that the recorded track would be ill due to the gaps left by turning the gps off

>  What if the GPS is not off but unavailable due to weak signal or being in a dead spot, how our app should behave?
I currently dont know. I think we should discuss this specific point in more details.

notes:
** If we want to focus on public transport agencies, I think we need to limit the scope of the routing to the area/city where the user currently is.

**Comment by carocad** [comment]
hive already requires gps location to do geocoding suggestions and directions
