### ISSUE TITLE
update expo cljs template to latest version

### ISSUE THREAD

**Issue by carocad** [hiposfer/hive#72]
This is related to: https://github.com/seantempesta/expo-cljs-template/issues/43

Since our app used the template from before the update to the figwheel bridge it is possible that there are some breaking changes.

**Comment by carocad** [comment]
If I recall correctly we created a new project based on the state of the template just before this commit: c907938a770828db01c92a0449a4e91c585e1339

**Comment by mehdisadeghi** [comment]
Do we really need to follow updates to that template? Merging changes scattered around a template back into hive is troublesome and error-prone. Templates are just starting points, and unlike dependencies are hard to update.

**Comment by carocad** [comment]
> Do we really need to follow updates to that template?

Unfortunately yes, we do. Not because of the template itself, but because of the interface changes that are both in the figwheel-bridge, in react-native packager and in the expo cli.

> Templates are just starting points, and unlike dependencies are hard to update.

Agree completely, but they are not the ending either 😉 .  Right now that template has the knowledge and bug fixes of several developers. More than what we can test individually. Furthermore, developing the interface for react native is not our main focus.

If the ecosystem would be perfectly stable I would agree with you and just move on. However we will most likely need those updates and bug fixes.

PS: by updating the template I just mean the `env` folder and the `figwheel-bridge.js`. As you correctly pointed out, the rest is just template stuff that we can safely ignore.
