### ISSUE TITLE
explain how does the app works in general

### ISSUE THREAD

**Issue by carocad** [hiposfer/hive#79]
Currently there are way too many things that only I know since I was developing the app alone

I will try to explain these things as good as possible either in the Wiki or directly in the namespaces

**Comment by mehdisadeghi** [comment]
@carocad I find namespace docs extremely useful when navigating the source code.

**Comment by carocad** [comment]
@mehdisadeghi thanks for the heads up. I will keep that in mind

**Comment by mehdisadeghi** [comment]
Never mind, not even Firefox has such comments for its 400000+ source files.

**Comment by carocad** [comment]
dont worry I am not planning to have 100% docs coverage 😉 

This ticket was only about the main pieces of the app. Those were already addressed in #81
