### ISSUE TITLE
consider implementing release channels

### ISSUE THREAD

**Issue by carocad** [hiposfer/hive#94]
follow up on #84 comment

https://docs.expo.io/versions/v26.0.0/distribution/release-channels

It seems that expo already supports this. I think this would be very useful and could speed up our development process.

There are two points that I think we would need to work out though.
- modify our CI scripts to automatically release the app on a branch push
- verify that our production release works as expected (the development version would not work since it requires a figwheel server, which would defeat the purpose of "rapid testing")

@mehdisadeghi would you like to (eventually) tackle this?

related wiki:
- https://github.com/cljsrn/cljsrn-org/wiki/Advanced-Compilation

**Comment by mehdisadeghi** [comment]
@carocad I think it would be great if we create one release per pr and later delete it. I have to try it though.

**Comment by mehdisadeghi** [comment]
Closed in #95
